name: Radioalma.com
favicon: null
layout_spectrum: 0.7936910835560411
typography_spectrum: 0.2532678903080523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5931714533362538
  lightness: 0.9277651014272124
  saturation: 0.7641913946717978
  rhythmicContrast: 0.6130900275893509
purpose: []
